### ISSUE TITLE
OCPP Implementation

### ISSUE THREAD

**Issue by goRaspy** [SmartEVSE/smartevse#1]
Hi,

Your works is great ! Did you already thought about implementation of "open charge point protocol" for smart EVSE ?

Regards,

**Comment by wido** [comment]
No, not really. I think nobody started any work on this.

It might be really simple that a additional controller simply sets a pin to high and if that pin is low no charging is allowed.

**Comment by tho-wa** [comment]
Yes that's a great idea, then the SmartEVSE could also be used for public charging.
There are multiple billing service providers that are compatible to OCCP.

**Comment by wido** [comment]
I think that #9 would help with this. I'm closing this one right now as when #9 is implemented people could add their external auth to SmartEVSE.
