### ISSUE TITLE
MAINS setting limits current also in Normal mode

### ISSUE THREAD

**Issue by JosDeGraeve** [SmartEVSE/smartevse#10]
When the Smart Evse is in "MODE Normal", the EV will not charge upto the MAX current set value, if the MAINS set value is lower than the MAX set Value.

Environment:
Smart EVSE is connected to single phase 230V 32A rated wiring, charged vehicle is Tesla Model S 75D facelift model with high capacity charger.  Charger cable is rated to 3F 32A - socket connection.  Smart mode is turned off - no current clamps connected.

Steps to reproduce
* Enter menu
* Set MODE to Smart.
* Set MAINS value to 25A ( is this also not the default ? )
* Set Mode to Normal
* MAINS setting is no longer visible in the MENU
* Set MAX setting to 32A
* Connect Charger to Car and start charging

Observed behaviour
* Car charges at 25A instead of at 32A
* Setting the max current in the car is not possible, it is fixed at max 25A

Expected behaviour
* Car charges at 32A when SmartEVSE is in mode Normal with MAX set to 32A
* Because the MAINS setting is only visible in Smart mode it is not logical for it to have any effect when not in Smart mode.

Current issue Workaround:
* Enter SmartEVSE menu
* Set Mode to Smart
* Set MAINS value to 32A
* Set Mode to Normal
* Set MAX value to 32A
=> Car charges at 32A

This issue had me searching for quite a while why my Tesla did not charge upto 32A.  It's only when Tesla Service notified me that my charger had a pilot signal for 25A when i expected it to have a pilot signal for 32A.

I found the workaround above but others might be affected by this issue as well.

Kind regards and tnx for this great project !

**Comment by mstegen** [comment]
Thanks for your detailed issue report.
I have fixed this in the next version, will be uploaded in a few days.
