### ISSUE TITLE
Xtal frequency

### ISSUE THREAD

**Issue by maximevince** [SmartEVSE/smartevse#21]
Hi there,

First of all, congrats on the great work.
Second, I'd like to know what the Xtal frequency is that you're using for the PIC.
From the code comments, I am assuming it's 16 MHz, is that correct?
It's not annotated in the schematics.

Thanks,
Maxime

**Comment by mstegen** [comment]
Thanks.
Yes it's running at 16Mhz, the PLL is currently not used.

**Comment by maximevince** [comment]
Thanks for specifying!
