### ISSUE TITLE
solar mode - start current immediately 

### ISSUE THREAD

**Issue by Tom9731** [SmartEVSE/smartevse#38]
Hello, is it possible to set a basic charge current of 6A in 'solar' mode and it will start charging immediately with the 6A (without any pv current).
If the PV supplies more current, it will increase the charge current.

Thx

Regards Tom

**Comment by mstegen** [comment]
At the moment this is not possible. It will wait for minimum 1A (START current) solar power on one of the phases before it starts charging (at 6A).

A workaround is to start charging in Smart mode, and then switch to Solar mode. Then it will keep charging at 6A, until the STOP timer runs out. You can set the STOP timer to Disabled, to keep charging at a minimum of 6A.
If your PV supplies more current it will then increase the charge current.

If you connect a (pushbutton) switch to the SW input of the SmartEVSE you can easily switch between Smart/Solar charging by pressing the button.

I hope this helps.

-Michael
